name: Run tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1']
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - name: Add Julia bin to GITHUB_PATH
        run: |
          echo "C:\\Users\\runneradmin\\.julia\\bin" >> $GITHUB_PATH
        shell: bash
      - name: Print path in bash
        run: |
          echo $PATH
        continue-on-error: true
        shell: bash
      - name: Print path in PowerShell
        run: |
          echo $env:PATH
        continue-on-error: true
        shell: pwsh
      - name: Print path in cmd
        run: |
          echo %PATH%
        continue-on-error: true
        shell: cmd
      - name: Try esm in bash
        run: esm -h
        continue-on-error: true
        shell: bash
      - name: Try esm in PowerShell
        run: esm -h
        continue-on-error: true
        shell: pwsh
      - name: Try esm in cmd
        run: esm -h
        continue-on-error: true
        shell: cmd
      - name: Try esm.cmd in cmd
        run: esm.cmd -h
        continue-on-error: true
        shell: cmd
      - name: Try esm.cmd in bash
        run: esm.cmd -h
        continue-on-error: true
        shell: bash
      - name: Try esm.cmd in PowerShell
        run: esm.cmd -h
        continue-on-error: true
        shell: pwsh
      - uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
